class UserException(Exception):
    pass


class UserNotFoundException(UserException):
    pass
